### ISSUE TITLE
working directory glitch

### ISSUE THREAD

**Issue by saerio** [miyucode/MaxPyOS#11]
# what is the problem?

double clicking the MaxPyOs.py file to run it causes it to crash in a few seconds beacus the working directory is set to the uer folder by default instead of the folder MaxPyOS is in

# any simular issues?  
no

# how to fix?  
get current path of file and set that as working directory

**Comment by miyucode** [comment]
I don't really understand your problem.
But honestly, MaxPyOS was an old project so I don't improve MaxPyOS anymore.
Thanks you for making a issue about it, I'll maybe fix it for fun lol
