### ISSUE TITLE
Probléme 

### ISSUE THREAD

**Issue by Plunder283** [miyucode/MaxPyOS#9]
Il manque le fichier Shell dans le Systeme.Shell.

Ps : Tu peux me débloquer mdr j'ai rien fait tu me bloque 😅

**Comment by miyucode** [comment]
Je ne t'ai pas bloqué et il ne manque pas le fichier dans le dossier.

**Comment by miyucode** [comment]
Correction: Je viens de me rendre compte que j'ai oublié de commit et de le push !

**Comment by miyucode** [comment]
C'est corrigé ! Merci de ta contribution au projet !
